/*
 Angelfish(tm) asynchronous tracking code for websites.

 Copyright (c) 2012 Actual Metrics. All Rights Reserved.
 http://www.angelfishstats.com
 v20130402.03
*/
var h=!0,i=null,n=!1,K="001";
(function(l,q,k,f,L){function D(a){if(!a||!a.url)return h;var b=escape(a.m?a.m:f.e),b=b+("="+d.visitorId+"."+d.visitStartTime),b=b+("."+g(e.source.replace(/\&/g,""))+"%26"+g(e.medium.replace(/\&/g,""))+"%26"+g(e.campaign.replace(/\&/g,""))+"%26"+g(e.keyword.replace(/\&/g,""))+"%26"+g(e.content.replace(/\&/g,"")));return 0<a.url.indexOf("?")?a.url+"&"+b:a.url+"?"+b}function g(a){return encodeURIComponent(decodeURIComponent(a.toString()))}function w(a,b){if(a&&!(0===a.length||"function"!==typeof b))for(var c in a)if(a.hasOwnProperty(c)&&
b(c)===n)break}function x(a,b,c,e){var d=a+"="+b+";";if(c){if("session"!==c){var r="";e&&(r=new Date,r.setTime(r.getTime()+e*("min"===c?6E4:864E5)),r=r.toUTCString());d+="expires="+r+";"}}else d+="expires=Thu, 01-Jan-1970 00:00:01 GMT;";f.g&&(d+="path="+f.g+";");"auto"!=f.f&&(d+="domain="+f.f+";");q.cookie=d;j[a]=b}function s(){return Math.ceil((new Date).getTime()/1E3)}function y(){var a=(e.keyword||"").replace(/\&/g,""),a=e.ie?a:g(a),a=d.visitorId+"&"+d.visitStartTime+"&"+d.lastActivityTime+"&"+
g((e.source||"").replace(/\&/g,""))+"&"+g((e.medium||"").replace(/\&/g,""))+"&"+g((e.campaign||"").replace(/\&/g,""))+"&"+a+"&"+g((e.content||"").replace(/\&/g,""));x(f.a.sessionInfo,a,"day",f.q);j[f.a.sessionTimeout]||E()}function E(){x(f.a.sessionTimeout,d.visitorId,"session")}function M(){if(!j[f.a.sessionInfo])return d.visitorType="new",n;var a=j[f.a.sessionInfo].split("&");d.visitorId=a[0];d.visitorType="returning";d.visitStartTime=parseInt(a[1],10);d.visitId=g(d.visitorId+(d.visitStartTime?
d.visitStartTime:s()).toString());d.lastActivityTime=a[2];e.source=a[3];e.medium=a[4];e.campaign=a[5];e.keyword=a[6];e.content=a[7];j[f.a.userDefined]?(a=j[f.a.userDefined].split("&"),a[0]==d.visitId&&(d.userDefined=a[1])):d.userDefined=i;return h}function N(){if(!o[f.e])return n;var a,b,c,t;a=o[f.e];b=a.indexOf(".");if(0<b)c=a.substring(0,b);else return n;t=a.indexOf(".",b+1);if(0<t)b=a.substring(b+1,t);else return n;a=a.substr(t+1);a=a.split("&");if(5!=a.length)return n;d.visitorId=c;d.visitStartTime=
b;d.visitId=g(d.visitorId+(parseInt(d.visitStartTime,10)?parseInt(d.visitStartTime,10):s()).toString());e.source=unescape(a[0]);e.medium=unescape(a[1]);e.campaign=unescape(a[2]);e.keyword=unescape(a[3]);e.content=unescape(a[4]);return h}function u(){if(!d.visitorId){var a=0,b;for(b=0;b<p.hostname.length;b++)a+=p.hostname.charCodeAt(b);d.visitorId=g((a+Math.floor(1E8*Math.random())).toString());E()}d.visitStartTime=s();d.lastActivityTime=d.visitStartTime;d.visitId=g(d.visitorId+(d.visitStartTime?d.visitStartTime:
s()).toString());d.pageviewCount=0;if(1!==f.p||!e.source)e=O()}function P(a){if(!a)return{hostname:"",queryParams:[],stem:""};var b,c,d,e="",f=[];b=a.indexOf("://");if(-1===b)return{r:n};b+=3;c=a.indexOf("/",b);-1===c?(c=a.indexOf("?",b),-1===c?d=a.substring(b):(d=a.substring(b,c),f=a.substring(c+1).split("&"))):(d=a.substring(b,c),b=c+1,c=a.indexOf("?",b),-1<c?(e=a.substring(b,c),f=a.substr(c+1).split("&")):e=a.substr(b));if(-1<(b=d.indexOf(":")))d=d.substring(0,b);return{hostname:d,queryParams:f,
stem:"/"+e}}function F(a){var b,c="",d=n,e,g,k,j,m;if(!a)return{r:n};var l=P(a);g=l.hostname;k=l.queryParams;c=g;g=g.split(".");if(0===g.length)return{r:n};for(a=0;a<g.length-1;a++)if(e=g[a],f.b[e]&&(c=a+1<g.length?e+"."+g[a+1]:e,d=h,j=z[e.toLowerCase()]?e.toLowerCase():n,m=n,w(k,function(a){a=k[a].split("=");return j&&a[0]===z[j].w&&(m=a[1].toLowerCase(),b)||a[0]===f.b[e]&&(c=e,b=a[1],!j||m)?n:h}),j&&!m&&(m=z[j]["default"]),b&&(!j||"utf8"==m||"utf-8"==m)))b=decodeURIComponent(b),m=j=n;return d&&
b!=i?(d={r:d,kw:b,hn:c},m&&(d.d=m),d):{r:d,hn:l.hostname}}function O(){var a={},b=q.referrer.replace("+","%20"),c,d,g={};for(c in f.c)if(f.c.hasOwnProperty(c)!=n)for(d in g[c]=i,f.c[c])if(f.c[c].hasOwnProperty(d)!=n&&(a=f.c[c][d],o[a])){g[c]=o[a];break}if(g.source&&g.medium&&g.campaign)a={source:g.source,medium:g.medium,campaign:g.campaign,keyword:"",content:g.content||""},g.keyword?a.keyword=g.keyword:(c=F(b),c.r&&"string"===typeof c.kw&&(a.keyword=c.kw));else{if(0===f.sourceOverwrite&&e.source&&
e.medium)return e;c=F(b);if(c.hn&&c.hn==l.location.hostname)return e;c.r&&"google"===c.hn&&"string"===typeof o.gclid?a={source:"google",medium:"cpc",campaign:"adwords",keyword:c.kw,content:""}:c.r?"string"===typeof c.kw?(a={source:c.hn,medium:"organic",campaign:"(organic)",keyword:c.kw||"(not provided)",content:""},c.d&&(a.d=c.d)):a={source:c.hn,medium:"referral",campaign:"(referral)",keyword:"",content:b}:a=c.hn?{source:c.hn,medium:"referral",campaign:"(referral)",keyword:"",content:b}:{source:"direct",
medium:"(none)",campaign:"",keyword:"",content:""}}a.d||(a.keyword=a.keyword.toLowerCase());return a}function G(){if(!A){for(A=h;v.length;){var a,b;a=v.shift();a.method&&(b=a.method,delete a.method,b(a))}setTimeout(G,500);A=n}}function Q(a){var b,c,g;b=a.page||p.pathname;c=b.indexOf(f.i);0<c&&(b=b.substr(0,c));var j=f.i;j||(j="?");c="?"==j?"#":"?";g=a.page||p.href;j=g.lastIndexOf(j);0<j?(g=g.substr(j+1),g=g.split(c),c=g[0]):c="";b={t:"pv",pv:b,tt:a.title||q.title,qr:c};b.vt=d.visitorType;b.sc=e.source;
b.md=e.medium;b.cp=e.campaign;b.kw=e.keyword;b.cn=e.content;e.ie&&(b.ie=e.ie);c=b;k&&(c.je=k.javaEnabled()?1:0);l&&l.screen&&(c.dp=l.screen.colorDepth,c.sh=l.screen.height,c.sw=l.screen.width);c=R();g=S();b.bn=c.name;b.bv=c.version;b.pn=g.name;g.version&&(b.pr=g.version);b.bl=k.language?k.language.toLowerCase():k.userLanguage?k.userLanguage.toLowerCase():"";b.js=B;b.hn=p.hostname||"(not set)";b=H(b);I(b);"function"==typeof a.callback&&(c=a.callback,delete a.callback,a.hit=b,c(a));0===d.pageviewCount&&
d.userDefined&&J({udv:d.userDefined});d.pageviewCount++}function J(a){var b;d.userDefined=a.udv;b=d.visitId+"&"+g(d.userDefined.replace(/\&/g,""));x(f.a.userDefined,b,"day",180);b={t:"udv",uv:d.userDefined};b=H(b);I(b);if("function"==typeof a.callback){var c=a.callback;delete a.callback;a.hit=b;c(a)}}function H(a){var b,c=[];b="auto"===f.h?p.protocol+"//":f.h?"https://":"http://";b+="auto"==f.j?l.location.hostname:f.j;b+=f.l;a.vi=d.visitorId;a.vs=d.visitId;a._=Math.floor(1E6*Math.random());a.v=K;
w(f.k,function(a){j[a]&&c.push(g(a+"="+j[a]))});a.ck=c.join(";");c=i;b+="?"+T(a);b.replace(/%20/g,"+");return b}function T(a){var b=[];w(a,function(c){a[c]&&("ie"==c||"kw"==c&&a.d?b.push(c+"="+a[c]):b.push(g(c)+"="+g(a[c])))});return b.join("&")}function I(a){C&&((new Image).src=a.replace(/%20/g,"+"))}function R(){if(!k||!k.userAgent)return{name:i,version:i};var a=k.userAgent,b;return(b=a.match(/MSIE (\d+\.\d+);/i))&&2<=b.length?{name:"Internet Explorer",version:parseFloat(b[1])}:(b=a.match(/(Firefox|Safari|Chrome|Opera)[\/\s](\d+\.\d+)/i))&&
3<=b.length?{name:b[1],version:parseFloat(b[2])}:{name:k.appName,version:k.appVersion}}function S(){if(!k||!k.userAgent)return{name:i,version:i};var a=k.userAgent,b=k.platform,c;return(c=a.match(/Windows\sNT\s(\d+\.\d+)/i))&&0<c.length?(a=parseFloat(c[1]),5===a?{name:"Windows",version:2E3}:5.1===a?{name:"Windows",version:"XP"}:5.2===a?{name:"Windows",version:"XP Professional"}:6===a?{name:"Windows",version:"Vista"}:6.1===a?{name:"Windows",version:7}:6.2===a?{name:"Windows",version:8}:{name:"Windows",
version:a||"(not set)"}):(c=a.match(/(iPod|iPad|iPhone).*?OS\s([0-9\_]+)/i))&&0<c.length?{name:c[1],version:c[2].replace(/_/g,".")}:-1<a.indexOf("PSP (PlayStation Portable)")?{name:"PSP"}:-1<a.indexOf("PLAYSTATION 3")?{name:"Playstation 3"}:-1<a.toLowerCase().indexOf("xbox")?{name:"XBox"}:-1<a.toLowerCase().indexOf("googletv")?{name:"Google TV"}:(c=a.match(/Android\s(\d+\.\d+)/i))&&0<c.length?(a=parseFloat(c[1]),{name:"Android",version:a}):(c=a.match(/BlackBerry(\d+)\//i))&&0<c.length?(a=parseFloat(c[1]),
{name:"BlackBerry",version:a}):(c=b.match(/Linux\s(.+)/i))&&0<c.length?{name:"Linux",version:c[1]}:(c=a.match(/Mac OS\s?X ((\d\.?)+)/i))&&0<c.length?{name:"Mac OS X",version:c[1]}:{name:b}}String.prototype.trim=function(){return this.replace(/^[\s\xA0]+/,"").replace(/[\s\xA0]+$/,"")};var C=h,v=[],A=n,d={},e={},j={},o={agfoff:0,agf_off:0,gclid:i},p=q.location,B=1,z={baidu:{"default":"gb2312",parameter:"ie"},google:{"default":"utf-8",parameter:"ie"}};l[L]={enable:function(){return C=h},disable:function(){C=
n;return h},setTrackingFile:function(a){if(!a)return n;f.l=a;return h},setTrackingHost:function(a){if(!a)return n;f.j=a;return h},setCookiePath:function(a){if(!a)return n;f.g=a;return h},setCookieDomain:function(a){if(!a)return n;f.f=a;return h},setQueryDelimiter:function(a){if(!a||"?"!=a&&"#"!=a)return n;f.i=a;return h},putCookiesInQuery:function(a){if("object"!=typeof a||!a.length)return n;f.k=a;return h},setHttps:function(a){if("boolean"!=typeof a&&"auto"!=a)return n;f.h=a;return h},addOrganicReferrer:function(a,
b){if(!a||!b)return n;f.b[a]=b;return h},removeOrganicReferrer:function(a){if(!a||!f.b[a])return n;delete f.b[a];return h},addQueryExclude:function(a){if(!a)return n;f.n.push(a);return h},pageview:function(a){"object"!=typeof a&&(a={});a.method=Q;v.push(a);return h},setUserDefined:function(a){if("object"!=typeof a||!a.udv)return n;a.method=J;v.push(a);return h},getVisitInfo:function(){return d?d:{}},getMarketingVariables:function(){return e?e:{}},saveMarketingVariables:function(a){a.source&&(e.source=
a.source);a.medium&&(e.medium=a.medium);a.campaign&&(e.campaign=a.campaign);a.keyword&&(e.keyword=a.keyword);a.content&&(e.content=a.content);e.source||(e.source="");e.medium||(e.medium="");e.campaign||(e.campaign="");e.keyword||(e.keyword="");e.content||(e.content="");y();return h},resetVisit:function(){u();y();return h},setTransferQuery:function(a){return a?(f.e=a,h):n},getTransferUrl:D,transferVisitor:function(a){if(!a||!a.url)return h;l.location=D(a);return n},setJSVersion:function(a){return a&&
!isNaN(a)&&a>B?(B=parseFloat(a),h):n}};(function(){var a=p.search.substring(1).split("&"),b,c;c=f.b.split(",");f.b={};for(b=0;b<c.length;b++){var d=c[b].split(":");f.b[d[0].trim()]=d[1].trim()}for(b=0;b<a.length;b++)c=a[b].split("="),o[c[0]]=decodeURIComponent(c[1]);if(o.u||o.s)return n;a=q.cookie.split(";");for(b=0;b<a.length;b++)if(c=a[b].split("="),2==c.length){var d=j,e=c[0].trim();c=c[1].trim();d[e]=decodeURIComponent(c)}b=[1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9];for(a=0;a<b.length;a++)q.write(unescape('%3Cscript language="Javascript'+
b[a]+'"%3Eagf.setJSVersion('+b[a]+");%3C/script%3E"));return h})()&&(N()||(M()?parseInt(d.lastActivityTime,10)+60*f.o<s()?u():j[f.a.sessionTimeout]||u():u()),d.lastActivityTime=s(),y(),G())})(window,document,navigator,{l:"/agf.gif",j:"auto",i:"?",k:[],h:"auto",b:"google:q,yahoo:p,msn:q,aol:q,lycos:query,ask:q,altavista:q,bing:q,netscape:query,cnn:query,looksmart:qt,about:terms,mamma:query,alltheweb:q,gigablast:q,voila:rdata,virgilio:qs,live:q,baidu:wd,alice:qs,yandex:text,najdi:q,club-internet:q,mama:query,seznam:q,search:q,wp:szukaj,onet:qt,netsprint:q,google.interia:q,szukacz:q,yam:k,pchome:q",
n:[],c:{source:["agfs"],medium:["agfm"],campaign:["agfc"],keyword:["agfk"],content:["agfr"]},p:0,a:{sessionInfo:"agfs",sessionTimeout:"agft",userDefined:"agfudv"},g:"/",f:"auto",o:30,q:180,e:"agfv"},"agf");
